name: Build and Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET 10
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Publish DLL
      run: dotnet publish -c Release -r linux-x64 --self-contained false -o ./publish

    - name: Deploy to Branch
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: ./publish
        branch: deploy # Hasil build ditaruh di branch ini
        
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /root/kang-nangkring
          git fetch origin deploy
          git reset --hard origin/deploy
          # Build image dan jalankan
          docker build -t bot-nangkring .
          docker stop bot-nangkring || true
          docker rm bot-nangkring || true
          docker run -d \
            --name bot-nangkring \
            --restart always \
            -e DiscordToken=${{ secrets.DISCORD_TOKEN }} \
            bot-nangkring