name: Build and Release

on:
  push:
    branches: [ master, main, MASTER ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
      
      - name: Publish Bot
        run: |
          dotnet publish -c Release -o ./publish
          cp Dockerfile ./publish/  
          cp start.sh ./publish/  

      - name: Deploy to Branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          branch: deploy
          folder: ./publish
          clean: true

      - name: Update VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: DISCORD_TOKEN # Gunakan fitur bawaan envs
          debug: true
          script: |
            cd ~/kang-nangkring || exit
            git fetch origin deploy
            git reset --hard origin/deploy
            docker build -t kang-nangkring .
            docker stop bot-nangkring 2>/dev/null || true
            docker rm bot-nangkring 2>/dev/null || true
            
            # Jalankan docker menggunakan variabel yang dikirim dari envs
            docker run -d \
              --name bot-nangkring \
              --restart always \
              --net=host \
              -e DiscordToken="$DISCORD_TOKEN" \
              kang-nangkring
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}